import { environmentFingerprint } from './schema.js';
import { stabilityCv } from './table.js';

/**
 * Self-contained HTML report for sharing (paste, email, GitHub gist, static host).
 * @param {Record<string, unknown>} report
 */
export function renderHtmlReport(report) {
  const fp = environmentFingerprint(report);
  const options = /** @type {Record<string, unknown>} */ (report.options ?? {});
  const tags = Array.isArray(options.tags) ? options.tags : [];
  const summary = /** @type {Array<Record<string, unknown>>} */ (report.summary ?? []);

  const esc = (s) => String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

  const metaRows = [
    ['Report ID', report.reportId ?? '—'],
    ['fm-bench', report.version ?? '—'],
    ['Schema', report.schemaVersion ?? 'legacy'],
    ['Started', report.startedAt ?? '—'],
    ['Finished', report.finishedAt ?? '—'],
    ['Profile', options.profile ?? '—'],
    ['Runs / prompt', options.runs ?? '—'],
    ['Concurrency', formatConcurrency(options)],
    ['Tags', tags.length ? tags.join(', ') : '—'],
    ['Note', options.note ?? '—'],
    ['Hardware', fp.hwModel ?? '—'],
    ['CPU', fp.cpuBrand ?? '—'],
    ['Memory', fp.memoryGb != null ? `${fp.memoryGb} GB` : '—'],
    ['macOS', fp.macOSProductVersion ?? '—'],
    ['Build', fp.macOSBuildVersion ?? '—'],
    ['Node', fp.node ?? '—'],
    ['fm CLI digest', fp.fmHelpDigest ?? '—'],
    ['Models', Object.entries(fp.modelIdentities).map(([name, identity]) => `${name} = ${identity}`).join(', ') || '—']
  ];

  const summaryRows = summary.map((row) => {
    const ttft = /** @type {{ p50?: number, p95?: number }} */ (row.ttft ?? {});
    const lat = /** @type {{ p50?: number, p95?: number }} */ (row.latency ?? {});
    const tps = /** @type {{ avg?: number }} */ (row.tokensPerSecond ?? {});
    return `<tr>
      <td>${esc(row.model)}</td>
      <td>${esc(row.concurrency ?? 1)}</td>
      <td>${row.available ? 'yes' : 'no'}</td>
      <td>${fmtPct(row.successRate)}</td>
      <td>${fmtPct(row.goodputRate)}</td>
      <td>${fmtMs(ttft.p50)}</td>
      <td>${fmtMs(ttft.p95)}</td>
      <td>${fmtMs(lat.p50)}</td>
      <td>${fmtMs(lat.p95)}</td>
      <td>${fmtNum(tps.avg)}</td>
      <td>${fmtPct(stabilityCv(row))}</td>
    </tr>`;
  }).join('\n');

  const jsonEmbed = esc(JSON.stringify(report, null, 2));

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>fm-bench report ${esc(report.reportId ?? '')}</title>
  <style>
    :root { --bg: #0f1419; --card: #1a2332; --text: #e7ecf3; --muted: #8b9cb3; --accent: #3d8bfd; --border: #2a3548; }
    * { box-sizing: border-box; }
    body { font-family: ui-sans-serif, system-ui, -apple-system, sans-serif; background: var(--bg); color: var(--text); margin: 0; padding: 2rem 1.25rem; line-height: 1.5; }
    h1 { font-size: 1.35rem; margin: 0 0 0.25rem; }
    .sub { color: var(--muted); font-size: 0.9rem; margin-bottom: 1.5rem; }
    section { background: var(--card); border: 1px solid var(--border); border-radius: 10px; padding: 1.25rem; margin-bottom: 1.25rem; }
    h2 { font-size: 1rem; margin: 0 0 1rem; color: var(--accent); }
    dl { display: grid; grid-template-columns: 10rem 1fr; gap: 0.35rem 1rem; margin: 0; font-size: 0.88rem; }
    dt { color: var(--muted); }
    dd { margin: 0; }
    table { width: 100%; border-collapse: collapse; font-size: 0.82rem; }
    th, td { text-align: left; padding: 0.45rem 0.5rem; border-bottom: 1px solid var(--border); }
    th { color: var(--muted); font-weight: 600; }
    pre { background: #0b0f14; border: 1px solid var(--border); border-radius: 8px; padding: 1rem; overflow: auto; font-size: 0.72rem; max-height: 320px; }
    footer { color: var(--muted); font-size: 0.8rem; margin-top: 2rem; }
    a { color: var(--accent); }
  </style>
</head>
<body>
  <h1>fm-bench benchmark report</h1>
  <p class="sub">Share this file to compare runs on identical prompt suites. Attach JSON for automation.</p>

  <section>
    <h2>Run metadata</h2>
    <dl>
      ${metaRows.map(([k, v]) => `<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('\n      ')}
    </dl>
  </section>

  <section>
    <h2>Summary by model</h2>
    <table>
      <thead>
        <tr>
          <th>Model</th><th>C</th><th>Avail</th><th>Success</th><th>Goodput</th>
          <th>TTFT P50</th><th>TTFT P95</th><th>E2E P50</th><th>E2E P95</th><th>User tok/s</th><th>CV</th>
        </tr>
      </thead>
      <tbody>
        ${summaryRows || '<tr><td colspan="11">No summary rows</td></tr>'}
      </tbody>
    </table>
  </section>

  <section>
    <h2>Embedded JSON (machine-readable)</h2>
    <pre>${jsonEmbed}</pre>
  </section>

  <footer>
    Generated by <a href="https://github.com/dvnold/fm-bench">fm-bench</a>.
    Compare two reports: <code>fm-bench compare before.json after.json</code>.
    Validate: <code>fm-bench validate report.json</code>.
  </footer>
</body>
</html>
`;
}

function formatConcurrency(options) {
  const sweep = options.sweepConcurrency;
  if (Array.isArray(sweep) && sweep.length > 0) return sweep.join(', ');
  return String(options.concurrency ?? 1);
}

function fmtMs(v) {
  if (!Number.isFinite(v)) return '—';
  return v >= 1000 ? `${(v / 1000).toFixed(2)}s` : `${Math.round(v)}ms`;
}

function fmtPct(v) {
  if (!Number.isFinite(v)) return '—';
  return `${Math.round(v * 100)}%`;
}

function fmtNum(v) {
  if (!Number.isFinite(v)) return '—';
  return String(Math.round(v * 10) / 10);
}